# Generated by Django 3.0.5 on 2022-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='comment',
        ),
        migrations.AddField(
            model_name='pizza',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
