# Generated by Django 3.0.5 on 2022-12-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20221211_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
